name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: glibc
            dockerfile: ./internal/integ/Dockerfile
          - name: musl
            dockerfile: ./internal/integ/Dockerfile.musl

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build -t go-pduckdb/integ-${{ matrix.name }} -f ${{ matrix.dockerfile }} .

      - name: Run integration tests
        run: docker run --rm go-pduckdb/integ-${{ matrix.name }}
